#!/usr/bin/env python3
"""Check every TRT stream, repair dead ones, regenerate the playlists.

Exit status is always 0; what changed is reported on stdout and in STATUS.md.

Status meanings
  ok       master playlist fetched and parsed
  geo      HTTP 403 - the stream is alive but restricted to Turkey
  dead     anything else (404, DNS failure, timeout, non-M3U body)

A "dead" channel triggers repair: the alternate hosts from channels.json are
probed and the first working one is promoted to the channel's host. A "geo"
channel is never touched, because a check run from outside Turkey sees 403 on
TRT 2, TRT Spor, TRT Spor Yildiz and TRT Belgesel by design.
"""

import json
import pathlib
import subprocess
import sys
from datetime import datetime, timezone

ROOT = pathlib.Path(__file__).resolve().parent
CONF = ROOT / "channels.json"
UA = "TurkishIPTV-Claude/1.0 (+https://github.com/kuz3-orange/TurkishIPTV-Claude)"
TIMEOUT = "20"


def probe(url):
    """Return (status, http_code, variants) for one master playlist URL."""
    proc = subprocess.run(
        ["curl", "-sL", "-m", TIMEOUT, "-A", UA, "-w", "\n%{http_code}", url],
        capture_output=True, text=True,
    )
    body, _, code = proc.stdout.rpartition("\n")
    code = code.strip() or "000"
    if code == "403":
        return "geo", code, []
    if code != "200" or not body.lstrip().startswith("#EXTM3U"):
        return "dead", code, []
    variants = sorted(
        {int(line.split("RESOLUTION=")[1].split("x")[1].split(",")[0])
         for line in body.splitlines() if "RESOLUTION=" in line}
    )
    return "ok", code, variants


def master(host):
    return f"https://{host}/master.m3u8"


def check_all(conf):
    results = []
    for ch in conf["channels"]:
        status, code, variants = probe(master(ch["host"]))
        repaired_from = None
        if status == "dead":
            for alt in ch.get("alt_hosts", []):
                alt_status, alt_code, alt_variants = probe(master(alt))
                if alt_status in ("ok", "geo"):
                    repaired_from = ch["host"]
                    ch["host"] = alt
                    status, code, variants = alt_status, alt_code, alt_variants
                    break
        results.append({
            "slug": ch["slug"], "name": ch["name"], "host": ch["host"],
            "status": status, "code": code, "variants": variants,
            "repaired_from": repaired_from,
        })
    return results


def extinf(conf, ch):
    return (
        f'#EXTINF:-1 tvg-id="{ch["tvg_id"]}" tvg-name="{ch["name"]}" '
        f'tvg-logo="{conf["logo_base"]}/{ch["slug"]}.png" '
        f'tvg-language="{ch["lang"]}" tvg-country="TR" '
        f'group-title="TRT",{ch["name"]}'
    )


def render(conf, header, path_fn):
    lines = [f'#EXTM3U x-tvg-url="{conf["epg"]}"', *header, ""]
    for ch in conf["channels"]:
        lines += [extinf(conf, ch), f'https://{ch["host"]}/{path_fn(ch)}', ""]
    return "\n".join(lines).rstrip() + "\n"


def write_playlists(conf):
    auto = render(conf, [
        "# TRT public channels - adaptive (auto) quality",
        "# Each URL is the HLS master playlist: the player picks the variant that",
        "# fits the connection (360p / 480p / 720p / 1080p / 1440p). No 4K exists.",
        "# Generated by update.py - edit channels.json, not this file.",
    ], lambda ch: "master.m3u8")
    hd = render(conf, [
        "# TRT public channels - locked to 1080p",
        "# For players that pick a poor variant on their own, or to stay below 1440p.",
        "# Needs roughly 7 Mbit/s per stream.",
        "# Generated by update.py - edit channels.json, not this file.",
    ], lambda ch: "master_1080.m3u8")
    (ROOT / "trt.m3u").write_text(auto, encoding="utf-8")
    (ROOT / "trt-1080p.m3u").write_text(hd, encoding="utf-8")


def write_status(results):
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    mark = {"ok": "OK", "geo": "GEO (TR only)", "dead": "DEAD"}
    rows = ["# Stream status", "", f"Last checked: {now}", "",
            "| Channel | Status | HTTP | Max | Host |",
            "| --- | --- | --- | --- | --- |"]
    for r in results:
        top = f'{r["variants"][-1]}p' if r["variants"] else "-"
        rows.append(f'| {r["name"]} | {mark[r["status"]]} | {r["code"]} | {top} | `{r["host"]}` |')
    repaired = [r for r in results if r["repaired_from"]]
    if repaired:
        rows += ["", "## Repaired this run", ""]
        rows += [f'- {r["name"]}: `{r["repaired_from"]}` -> `{r["host"]}`' for r in repaired]
    rows += ["", "GEO means the stream is alive but TRT only serves it inside Turkey;",
             "a check run from outside Turkey always reports it that way.", ""]
    (ROOT / "STATUS.md").write_text("\n".join(rows), encoding="utf-8")


def main():
    conf = json.loads(CONF.read_text(encoding="utf-8"))
    results = check_all(conf)
    CONF.write_text(json.dumps(conf, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    write_playlists(conf)
    write_status(results)

    for r in results:
        note = f'  (was {r["repaired_from"]})' if r["repaired_from"] else ""
        print(f'{r["status"]:5} {r["code"]}  {r["name"]:<18} {r["host"]}{note}')
    dead = [r["name"] for r in results if r["status"] == "dead"]
    if dead:
        print("\nUNREPAIRED: " + ", ".join(dead), file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
